[project]
name = "fancy-restaurant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "django>=5.2.16",
]

[dependency-groups]
dev = [
    "black>=26.5.1",
    "coverage>=7.15.0",
    "pylint>=4.0.6",
    "pytest>=9.1.1",
    "pytest-django>=4.12.0",
]
