# Generated by Django 5.2.16 on 2026-07-23 15:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("table_number", models.PositiveIntegerField(unique=True)),
                (
                    "capacity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["capacity", "table_number"],
                "indexes": [
                    models.Index(
                        fields=["capacity", "table_number"],
                        name="reservation_capacit_2f796b_idx",
                    ),
                    models.Index(
                        fields=["is_active", "capacity"],
                        name="reservation_is_acti_4c9741_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField(unique=True)),
                (
                    "duration_minutes",
                    models.PositiveIntegerField(
                        default=90,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["start_time"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "start_time"],
                        name="reservation_is_acti_0037e2_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100)),
                ("reservation_date", models.DateField(db_index=True)),
                (
                    "guest_count",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="confirmed",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "table",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="reservations.table",
                    ),
                ),
                (
                    "time_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reservations",
                        to="reservations.timeslot",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "reservation_date",
                    "time_slot__start_time",
                    "table__table_number",
                ],
                "indexes": [
                    models.Index(
                        fields=["reservation_date", "status"],
                        name="reservation_reserva_4f8570_idx",
                    ),
                    models.Index(
                        fields=["customer_name"], name="reservation_custome_1e343c_idx"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation_date", "time_slot", "table"),
                        name="unique_reservation_table_slot",
                    )
                ],
            },
        ),
    ]
