# Generated by Django 5.2.16 on 2026-07-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0003_simplify_reservation_schema"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.UniqueConstraint(
                condition=models.Q(("login", ""), _negated=True),
                fields=("login",),
                name="unique_nonempty_customer_login",
            ),
        ),
    ]
